### ISSUE TITLE
Emails Spam Classifier

### ISSUE THREAD

**Issue by souravsasmal01** [kishanrajput23/Programming-Resources#41]

**Comment by souravsasmal01** [comment]
prime or Not

#include <stdio.h>

int main() {

  int n, i, flag = 0;
  printf("Enter a positive integer: ");
  scanf("%d", &n);
 0 and 1 are not prime numbers
  // change flag to 1 for non-prime number
  if (n == 0 || n == 1)
    flag = 1;

  for (i = 2; i <= n / 2; ++i) {

    // if n is divisible by i, then n is not prime
    // change flag to 1 for non-prime number
    if (n % i == 0) {
      flag = 1;
      break;
    }
}  }

  // flag is 0 for prime numbers
  if (flag == 0)
    printf("%d is a prime number.", n);
  else
    printf("%d is not a prime number.", n);

  return 0;
}

**Comment by souravsasmal01** [comment]
[spam.csv](https://github.com/kishanrajput23/Programming-Resources/files/9793537/spam.csv)
[README.md](https://github.com/kishanrajput23/Programming-Resources/files/9793539/README.md)

**Comment by bhavyagupta-11** [comment]
Hii , Kindly assign this issue to me

**Comment by souravsasmal01** [comment]
Ok
